### ISSUE TITLE
Create prerelease branch

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/certifi-feedstock#19]
I am looking to create a Python 3.6 package of certifi in order to eventually produce Python 3.6 packages of pip, setuptools, and wheels.  I think all of these should be uploaded to Anaconda.org with the `prerelease` label to match the current [Python 3.6.0 pre-releases](https://anaconda.org/conda-forge/python/files?channel=prerelease).  Could a `prerelease` branch be created in this feedstock in order to facilitate this task?   PR #18 tests the feasibility of this plan.

**Comment by ocefpaf** [comment]
Now Python 3.6 has landed already, but I strongly agree with this.

**Comment by jjhelmus** [comment]
closing.  A Python 3.6 build was created by #23.  Thanks @ocefpaf for the rerendering.
